#!/usr/bin/env bash

set -e

sock=/tmp/tmate.sock

new_session() {
    tmate -S $sock new-session -d     # Launch tmate in a detached state
    tmate -S $sock wait tmate-ready   # Blocks until the SSH connection is established
}

attach() {
    tmate -S $sock attach
}

tmate_address() {
    tmate -S $sock display -p '#{tmate_ssh}' 2>&1
}

tmate_address_ro() {
    tmate -S $sock display -p '#{tmate_ssh_ro}' 2>&1
}

tmate_address_html() {
    local addr=$(echo $(tmate_address))
    local link=$(echo $addr | cut -d ' ' -f 2 | cut -d '@' -f 1)
    echo https://tmate.io/t/$link
}

tmate_address_html_ro() {
    local addr=$(echo $(tmate_address_ro))
    local link=$(echo $addr | cut -d ' ' -f 2 | cut -d '@' -f 1)
    echo https://tmate.io/t/$link
}

# Usage: slack channel user_to_post_as "message" webhook
slack() {
    curl -sS -o /dev/null -X POST --data-urlencode \
         "payload={\"channel\": \"#$1\", \"username\": \"$2\", \"icon_emoji\": \":$2:\", \"text\": \"$3\"}" $4
}

# Usage: invite channel user
invite() {
    local user=`git config --get user.email | cut -d '@' -f 1`
    local address=`tmate_address`

    if [[ ! -z `echo $address | grep failed` ]]; then
        echo "Failed to connect to tmate server. Is this session dead?"
        exit 1
    fi

    slack $1 pair "Hey, <@$2>...want to pair? Join $user in this <`echo ${address/ /:\/\/}`|tmate session>." $SLACK_WEBHOOK
}

help() {
    tmate list-commands
    printf "\ntmate-wrapper enhancements:\n"
    printf "\taddress\n"
    printf "\taddress-html\n"
    printf "\taddress-html-ro\n"
    printf "\taddress-ro\n"
    printf "\tattach\n"
    printf "\thelp\n"
    printf "\tslack channel user\n"
    printf "\tversion\n"
}

if [[ $# -eq 0 ]]; then
    new_session
    attach
elif [[ $1 == "attach" ]]; then
    attach
elif [[ $1 == "slack" ]]; then
    invite $2 $3
elif [[ $1 == "address" ]]; then
    echo `tmate_address`
elif [[ $1 == "address-ro" ]]; then
    echo `tmate_address_ro`
elif [[ $1 == "address-html" ]]; then
    echo `tmate_address_html`
elif [[ $1 == "address-html-ro" ]]; then
    echo `tmate_address_html_ro`
elif [[ $1 == "help" || $1 == "-h" ]]; then
    help
elif [[ $1 == "version" ]]; then
    tmate -V
else
    tmate "$@"
fi
