#!/usr/bin/env bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

echo RAILS ENV $RAILS_ENV

echo Clear Old Data
script/data/all_clear

echo Load User Data
script/data/user_load

echo Load GH data
script/data/gh_load

echo Load Bids
bundle exec script/data/bid_load

echo Load Asks
bundle exec script/data/ask_load

echo Load Contracts
bundle exec script/data/contract_load

echo Done.
