#!/usr/bin/env ruby

require './config/environment'

Repo.destroy_all
User.destroy_all
Offer.destroy_all
Escrow.destroy_all
Position.destroy_all
Amendment.destroy_all
Contract.destroy_all
EventLine.destroy_all
