#!/usr/bin/env ruby

require "./config/environment"

puts "Users:     #{User.count}"
puts "Repos:     #{Repo.count}"
puts "Bugs:      #{Bug.count}"
puts "Bids:      #{Offer::Bid.count}"
puts "Asks:      #{Offer::Ask.count}"
puts "Contracts: #{Contract.count}"
