#!/usr/bin/env ruby

require "./config/environment"

puts "Users:      #{User.count}"
puts "Repos:      #{Repo.count}"
puts "Bugs:       #{Bug.count}"
puts "BU Offers:  #{Offer::Buy::Unfixed.count}"
puts "BF Offers:  #{Offer::Buy::Fixed.count}"
puts "Contracts:  #{Contract.count}"
puts "Positions:  #{Position.count}"
puts "Escrows:    #{Escrow.count}"
puts "Amendments: #{Amendment.count}"
