#!/usr/bin/env bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

pkill -f bot_buy
rm -f /tmp/bugm_day_jump

echo "----- BUGMARK TOTAL REBUILD ---------------------"
echo "START `date`"

echo RAILS ENV $RAILS_ENV

echo Clear Old Data
script/data/all_clear

echo Load User Data
script/data/user_load

echo Load GH data
script/data/gh_load

echo Load Offers to BuyUnfixed
bundle exec script/data/unfixed_load

echo Load Offers to BuyFixed
bundle exec script/data/fixed_load

echo Load Contracts
bundle exec script/data/contract_load

echo Counts
bundle exec script/data/all_count

echo "DONE `date`"
