#!/usr/bin/env ruby

require "./config/environment"

opts = [
  {
    bug_id:               Bug.first.id  ,
    token_value:          30            ,
    user_id:              User.first.id ,
    contract_maturation:  Time.now + 1.week
  },
  {
    bug_id:               Bug.first.id  ,
    token_value:          25            ,
    user_id:              User.first.id ,
    contract_maturation:  Time.now + 1.hour
  },
  {
    bug_id:               Bug.first.id  ,
    token_value:          15            ,
    user_id:              User.first.id ,
    contract_maturation:  Time.now + 1.day
  },
  {
    bug_id:               Bug.first.id  ,
    token_value:          20            ,
    user_id:              User.first.id ,
    contract_maturation:  Time.now - 1.hour
  }
]

opts.each do |opt|
  FG.create(:ask, opt)
end
