#!/usr/bin/env ruby

require "./config/environment"

opts = [
  {
    bug_id:               Bug.second.id  ,
    price:                0.90           ,
    volume:               5              ,
    user_id:              User.second.id ,
    contract_maturation:  Time.now + 1.hour
  },
  {
    bug_id:               Bug.third.id  ,
    price:                0.50          ,
    volume:               1             ,
    user_id:              User.first.id ,
    contract_maturation:  Time.now + 1.hour
  },
  {
    bug_id:               Bug.first.id  ,
    price:                0.75          ,
    volume:               10            ,
    user_id:              User.third.id ,
    contract_maturation:  Time.now + 1.day
  },
  {
    bug_id:               Bug.third.id  ,
    price:                0.20          ,
    volume:               2             ,
    user_id:              User.first.id ,
    contract_maturation:  Time.now - 1.hour
  },
  {
    bug_id:               Bug.second.id  ,
    price:                0.50           ,
    volume:               2              ,
    user_id:              User.third.id  ,
    contract_maturation:  Time.now - 1.hour
  },
  {
    bug_id:               Bug.second.id  ,
    price:                0.10           ,
    volume:               10             ,
    user_id:              User.first.id  ,
    contract_maturation:  Time.now - 1.hour
  },
  {
    bug_id:               Bug.second.id  ,
    price:                0.10           ,
    volume:               5              ,
    user_id:              User.third.id  ,
    contract_maturation:  Time.now - 1.hour
  }
]

opts.each do |opt|
  FG.create(:bid_buy, opt)
end
