#!/usr/bin/env ruby

require './config/environment'

json = File.read('script/data/BZsm.json')

tracker_name = "Mozilla/SeaMonkey"

Tracker.find_by_name(tracker_name).try(:destroy)

tracker = Tracker.create(name: tracker_name, type: "Tracker::BugZilla")

JSON.parse(json)["bugs"].each do |el|
  attrs = {
    type:      "Issue::BugZilla"           ,
    tracker_id:   tracker.id                   ,
    title:     el["summary"]             ,
    status:    el["status"]              ,
    synced_at: Time.now
  }
  Issue.create attrs
end
