#!/usr/bin/env ruby

require 'nokogiri'
require './config/environment'

xml = File.read('script/data/CVE.xml')

doc = Nokogiri::XML(xml) 
doc.remove_namespaces!

tracker_name = "Mitre/CVE"

Tracker.find_by_name(tracker_name).try(:destroy)

tracker = Tracker.create(name: tracker_name, type: "Tracker::Cvrf")

list = doc.search("//Vulnerability")

list.each do |el|
  note        = el.css('Note[Type="Description"]')
  description = note.first&.text&.gsub("\n"," ") || "NA"
  attrs = {
    type:    "Issue::Cvrf",
    tracker_id: tracker.id,
    title:   el.css('Title').first&.text,
    status:  "NA",
    synced_at: Time.now
  }
  Issue.create attrs
end

