#!/usr/bin/env ruby

require "./config/environment"

week_ends = BugmTime.future_week_ends

opts = [
  {
    stm_bug_id:  Bug.second.id       ,
    price:       0.10                ,
    volume:      45                  ,
    user_id:     User.first.id       ,
    maturation:  week_ends.first
  },
  {
    stm_bug_id:  Bug.third.id        ,
    price:       0.50                ,
    volume:      35                  ,
    user_id:     User.second.id      ,
    maturation:  week_ends.first
  },
  {
    stm_bug_id:  Bug.first.id        ,
    price:       0.25                ,
    volume:      20                  ,
    user_id:     User.last.id        ,
    maturation:  week_ends.first
  },
  {
    stm_bug_id:  Bug.third.id        ,
    price:       0.80                ,
    volume:      25                  ,
    user_id:     User.last.id        ,
    maturation:  week_ends.first
  },
  {
    stm_bug_id:  Bug.first.id        ,
    price:       0.50                ,
    volume:      35                  ,
    user_id:     User.last.id        ,
    maturation:  week_ends.first
  }
]

opts.each do |opt|
  base = {
    poolable:   false          ,
    aon:        false          ,
    stm_status: 'closed'
  }
  FB.create(:offer_bf, opt.merge(base))
end
