#!/usr/bin/env ruby

require "./config/environment"

opts = [
  {
    stm_bug_id:  Bug.second.id       ,
    price:       0.10                ,
    volume:      5                   ,
    user_id:     User.first.id       ,
    maturation:  Time.now + 1.week
  },
  {
    stm_bug_id:  Bug.third.id        ,
    price:       0.50                ,
    volume:      1                   ,
    user_id:     User.second.id      ,
    maturation:  Time.now + 1.hour
  },
  {
    stm_bug_id:  Bug.first.id        ,
    price:       0.25                ,
    volume:      10                  ,
    user_id:     User.last.id        ,
    maturation:  Time.now + 1.day
  },
  {
    stm_bug_id:  Bug.third.id        ,
    price:       0.80                ,
    volume:      2                   ,
    user_id:     User.last.id        ,
    maturation:  Time.now - 1.hour
  },
  {
    stm_bug_id:  Bug.first.id        ,
    price:       0.50                ,
    volume:      2                   ,
    user_id:     User.last.id        ,
    maturation:  Time.now - 1.hour
  }
]

opts.each do |opt|
  base = {
    poolable:   false          ,
    aon:        false          ,
    stm_status: 'closed'
  }
  FG.create(:offer_bf, opt.merge(base))
end
