#!/usr/bin/env ruby

require './config/environment'

def sync(name)
  opts = {
    name: name               ,
    type: "Repo::GitHub"
  }

  repo_cmd = RepoCmd::GhCreate.new(opts)
  repo_cmd.cmd_cast
  binding.pry
  item = RepoCmd::GhSync.from_repo(repo_cmd.repo)
  item.cmd_cast
end

# %w(mvscorg/bugmark mvscorg/bugmark-guides mvscorg/bugmark-slides elixir-lang/gen_stage elixir-lang/flow elixir-lang/gettext rust-lang/regex filterbubbler/filterbubbler-web-ext filterbubbler/filterbubbler-wp-plugin).each do |name|
%w(mvscorg/bugmark mozilla/bugmark-docs).each do |name|
  puts "Loading #{name}"
  sync(name)
end

