#!/usr/bin/env ruby

require './config/environment'

def sync(name)
  opts = {
    name: name               ,
    type: "Tracker::GitHub"
  }

  tracker_cmd = TrackerCmd::GhCreate.new(opts)
  tracker_cmd.project
  item = TrackerCmd::GhSync.from_tracker(tracker_cmd.tracker)
  item.project
end

# %w(mvscorg/bugmark mvscorg/bugmark-guides mvscorg/bugmark-slides elixir-lang/gen_stage elixir-lang/flow elixir-lang/gettext rust-lang/regex filterbubbler/filterbubbler-web-ext filterbubbler/filterbubbler-wp-plugin).each do |name|
%w(bugmark/bmx_cl_ruby bugmark/bmx_api_ruby bugmark/exchange bugmark/bugmark_docs).each do |name|
  puts "Loading #{name}"
  sync(name)
end

