#!/usr/bin/env ruby

puts 'loading rails...'
require __dir__ + '/../config/environment'

count = User.sans_avatar.count

devlog "Generating #{count} avatars"

User.sans_avatar.all.each do |x|
  x.add_default_avatar
  print '.'.green
  $stdout.flush
end
puts " \ndone."
