#!/usr/bin/env ruby

require_relative './reload_db'

reload_db 'recert'

devlog "RAILS_ENV = #{Rails.env}"

def dsload(klas, file)
  klas.new(file).import
end

devlog 'BAMRU'
dsload CfgCertTypeImporter          , 'data/import/orgs/SMSO/teams/bamru/bootstrap/cfg_qual_ctypes.csv'
dsload MembershipCertImporter       , 'data/import/orgs/SMSO/teams/bamru/members/certs.csv'

pmsg 'done'
