#!/usr/bin/env bash

cap production app:disable

ssh deploy@bugmark 'sudo stop bugmark'

ssh deploy@bugmark 'killall -9 ruby'

ssh deploy@bugmark 'cd a/bugmark/current ; script/recsv build'

ssh deploy@bugmark 'sudo start bugmark'

sleep 2

cap production app:enable

echo '----- system is enabled'

alert ding

sleep 5

ssh deploy@bugmark 'cd a/bugmark/current ; script/reavatar'

echo '---done'

alert ring
