#!/usr/bin/env bash

cap production app:disable

ssh deploy@Lica 'sudo stop ListCall'

ssh deploy@Lica 'killall -9 ruby'

ssh deploy@Lica 'cd a/Lica/current ; script/recsv build'

ssh deploy@Lica 'sudo start ListCall'

sleep 2

cap production app:enable

echo '----- system is enabled'

alert ding

sleep 5

ssh deploy@Lica 'cd a/Lica/current ; script/reavatar'

echo '---done'

alert ring
