#!/usr/bin/env ruby

require "./config/environment"

UserCmd::Create.new(email: "admin@bugmark.net", password: "bugmark").project

FB.create :user, email: "test1@bugmark.net"
FB.create :user, email: "test2@bugmark.net"
FB.create :user, email: "test3@bugmark.net"
FB.create :user, email: "joe@bugmark.net"
FB.create :user, email: "jane@bugmark.net"
