#!/usr/bin/env ruby

require 'nokogiri'
require 'pry'

xml = File.read('cve_2008.xml')

# doc = Nokogiri::Slop(xml)
doc = Nokogiri::XML(xml)
binding.pry
doc.remove_namespaces!
binding.pry
x = 1

# puts doc.root.children

# obj = doc.xpath('//DocumentNotes')
# obj = doc.xpath('.//DocumentNotes')
# obj = doc.search("//Note")
# obj = doc.xpath('//DocumentNotes')
# obj = doc.xpath('//Vulnerability', 'Vulnerability' => "http://www.icasi.org/CVRF/schema/vuln/1.1")
# obj = doc.xpath('//xmlns:Vulnerability')
obj = doc.css('//Notes')
# obj = doc.css('item')

puts obj.class
puts obj.length
# obj.each {|ele| puts ele}
