#!/usr/bin/env ruby

require './config/environment'

xml = File.read('script/data/cve_short.xml')

doc = Nokogiri::XML(xml) do |config|
  config.huge
end

repo_name = "Mitre/CVE"

Repo.find_by_name(repo_name).try(:destroy)

repo = Repo.create(name: repo_name, format: "CVRF")

# obj = doc.xpath('//DocumentNotes')
# obj = doc.xpath('.//DocumentNotes')
# obj = doc.search("//Note")
# obj = doc.xpath('//DocumentNotes')
# obj = doc.css('DocumentNotes')
# obj.each {|ele| puts ele}
obj = doc.css('item')

puts obj.last

obj.each do |el|
  attrs = {
    api_url:   el["url"]       ,
    http_url:  el["http_url"]  ,
    repo_id:   repo.id         ,
    title:     el["title"]     ,
    labels:    el["labels"]    ,
    status:    el["state"]     ,
    synced_at: Time.now
  }
  Issue.create attrs
end

