#!/usr/bin/env bash

# Run ansible on localhost

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR

ansible-playbook -i "localhost," -c local ~/src/bugmark/script/dev/provision/playbook/development.yml

