# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bmx.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bmx.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "bmx.HelloReply" do
    optional :message, :string, 1
  end
end

module Bmx
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmx.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmx.HelloReply").msgclass
end
