#!/usr/bin/env bash

# creates a tmux console that can be shared across multiple clients

# the console is defined in a setup file, referenced by $1
# the setup file must define '$APP' and 'create_new_session()'
# if no args are given, a default console is rendered

if [ -z $1 ] ; then
  export APP="console"
  create_new_session()
  {
    tmux new-session -s $APP -d    
  }
else
  export SRC_DIR=`dirname $1`
  export ABS_SRC_DIR=`cd $SRC_DIR ; pwd`
  source $1
fi

# create a new session if none exists
tmux has-session -t $APP # 2> /dev/null
if [ $? != 0 ] ; then
  echo "CREATING SESSION"
  create_new_session
fi

# get a count of active clients
count=`tmux list-clients | grep $APP | wc -l`

# if there are no clients, then attach directly to the session
if [ $count == 0 ] ; then
  tmux attach -t $APP
  exit $?
fi

# if there are attached clients, then attach using a Grouped
# Session (this enabled different clients to view different pages)
while [ true ] ; do  # loop until an available client-id is found...
  client_count=`tmux list-clients | grep $APP$count | wc -l`
  session_count=`tmux list-sessions | grep $APP$count | wc -l`
  if [ $client_count == 0 ] ; then
    [ $session_count != 0 ] && tmux kill-session -t $APP$count
    tmux new-session -t $APP -s $APP$count -d
    tmux select-window -t $APP$count:1
    tmux attach -t $APP$count
    exit $? 
  fi
  count=`expr $count + 1`
done
