#!/usr/bin/env bash

# Installs ansible on the local machine

# Abort if the ansible executable is found

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

echo "=== ANSIBLE INSTALL ====================================="
echo "Installing Python Dependencies"
sudo apt-get install software-properties-common -y -q
echo "Add ansible PPA"
sudo apt-add-repository ppa:ansible/ansible
echo "Apt Update"
sudo apt-get update
echo "Install Ansible"
sudo apt-get install ansible -y -q
echo "Install Ansible config file"
cat script/provision/ansible.cfg | sed -e's/ANSIBLEUSR/$USER/g' > ~/.ansible.cfg
echo "DONE."
