#!/usr/bin/env ruby

this_dir = File.expand_path(File.dirname(__FILE__))
lib_dir  = File.join(this_dir, 'lib')
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'grpc'
require 'hello_services_pb'

# HelloServer is simple server that implements the Hello server.
class HelloServer < Helloworld::Hello::Service
  # say_hello implements the SayHello rpc method.
  def say_hello(hello_req, _unused_call)
    Helloworld::HelloReply.new(message: "Hello #{hello_req.name}")
  end
end

# main starts an RpcServer that receives requests to HelloServer at the sample
# server port.
def main
  creds = GPRC::Core::Credentials.new(load_certs)
  s = GRPC::RpcServer.new
  # s.add_http2_port('0.0.0.0:50051', :this_port_is_insecure)
  s.add_http2_port('0.0.0.0:50051', creds)
  s.handle(HelloServer)
  s.run_till_terminated
end

main
