#!/usr/bin/env bash

# backup_sysdir

abort() {
  echo "ERROR: ONLY RUNS ON PRODUCTION!"
  exit 1
}

echo "||||||||||||||||||||||||||||"
echo ------- start sysdir backup -------
date
echo PWD is `pwd`
echo USER is `whoami`
echo ----------------------------

. ./.env

[[ "$RAILS_ENV" == "production" ]] || abort

bundle exec rake data:backup:sysdir

echo ------- finish backup ------
date
echo ----------------------------

