#!/usr/bin/env bash

# start the djest server

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

clear
echo "script/dev/djest"
cd dapp
echo "JEST SERVER FOR DAPP UNDER CONSTRUCTION..."
