#!/usr/bin/env bash

# run the development server

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

export APP="BUGMARK"

clear
echo "script/dev/puma"
#reset
bundle exec spring stop > /dev/null 2>&1
bundle exec spring rails server Puma --binding 0.0.0.0 --port 3000
#reset
