#!/usr/bin/env bash

# run the development server

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

export APP="BUGMARK"

clear
echo "script/dev/server"
webpack-dev-server --host $SYSNAME --port 9090
