#!/usr/bin/env bash

# run the development server

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

export APP="BUGMARK"

clear
echo "script/dev/server"
# webpack-dev-server --host $SYSNAME --public #--port 9091
webpack-dev-server --host 192.168.1.77
