#!/usr/bin/env ruby

# GRPC Client

lib_dir = File.join(__dir__, 'lib')
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'grpc'
require 'bmx_services_pb'

require 'client/intercept'

def main
  opts = {interceptors: [Client::Intercept.new]}
  stub = Bmx::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure, opts)
  # stub = Bmx::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure)
  user = ARGV.size > 0 ?  ARGV[0] : 'world'
  message = stub.say_hello(Bmx::HelloRequest.new(name: user)).message
  p "Greeting: #{message}"
end

main
