#!/usr/bin/env ruby

# GRPC Server

lib_dir = File.join(__dir__, 'lib')
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'grpc'
require 'bmx_services_pb'

require 'server/intercept'

# Base Server
class BmxServer < Bmx::Greeter::Service
  # say_hello implements the SayHello rpc method.
  def say_hello(hello_req, _unused_call)
    Bmx::HelloReply.new(message: "Hello #{hello_req.name}")
  end
end

# main starts an RpcServer that receives ding requests to HelloServer at the
# sample server port.
def main
  # s = GRPC::RpcServer.new(interceptors: [Server::Intercept.new])
  s = GRPC::RpcServer.new
  s.add_http2_port('0.0.0.0:50051', :this_port_is_insecure)
  s.handle(BmxServer)
  s.run_till_terminated
end

main
