#!/usr/bin/env bash
# should be called from tmux_console

export APP="xmguard"

create_new_session()
{

  cd /home/aleak/lr/MvscIM

  tmux new-session -s $APP -n GUARD -d

  tmux send-keys -t $APP:1 'cls ; cd /home/aleak/lr/MvscIM ; RUBYOPT=W0 bundle exec guard -c'  C-m

}

