#!/usr/bin/env bash

# Run ansible on localhost

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

ansible-playbook -i "localhost," -c local config/provision/Mvscim_development.yml

