#!/usr/bin/env ruby

# contract_resolve

require "./config/environment"

Contract.pending_resolution.each do |contract|
  puts "RESOLVING CONTRACT #{contract.id}"
  CmContractResolve.new(contract).save
end
