#!/usr/bin/env bash

# download_backup

abort() {
  echo "ERROR: ONLY RUNS ON DEVELOPMENT!"
  exit 1
}

echo "||||||||||||||||||||||||||||"
echo ------- start backup download -------
date
echo PWD is `pwd`
echo USER is `whoami`
echo ----------------------------

. ./.env 2> /dev/null
. ~/.bashrc

[[ "$RAILS_ENV" == "development" ]] || abort

rsync -av deploy@lch1:var/backup/bugmark/lch1 ~/var/backup/bugmark --delete

echo ------- finish download ------
date
echo ----------------------------

