#!/usr/bin/env ruby

abort('usage: script/gen_env_chruby <username> [<env>] > .env-chruby') if ARGV.length == 0

usr = ARGV[0]
env = ARGV[1] || 'dev'
vsn = File.read('.ruby-version').strip
usrpr = "/home/#{usr}/.rubies"
usrpg = "/home/#{usr}/.gem"
based = "/home/#{usr}/src/bugmark"             # for production
share = "#{based}/shared/bundle/ruby/#{vsn}"   # for production
cpath = "#{usrpg}/ruby/#{vsn}/bin:#{usrpr}/ruby-#{vsn}/lib/ruby/gems/2.1.0/bin:#{usrpr}/ruby-#{vsn}/bin:./bin"

opts = {
  CHRUBY_USER:  usr,
  CHRUBY_PATH:  cpath,
  RUBY_VERSION: vsn,
  RUBY_ENGINE:  'ruby',
  RUBY_ROOT: "#{usrpr}/ruby-#{vsn}",
  GEM_HOME:  "#{usrpg}/ruby/#{vsn}",
  GEM_ROOT:  "#{usrpr}/ruby-#{vsn}/lib/ruby/gems/2.1.0",
  GEM_PATH:  "#{usrpg}/ruby/#{vsn}:#{usrpr}/ruby-#{vsn}/lib/ruby/gems/2.1.0",
  USR_HOME:  "/home/#{usr}",
  PATH: "#{cpath}:#{ENV["PATH"]}"
}

if env != 'dev'
  opts[:GEM_HOME] = "#{based}/shared/bundle/ruby/#{vsn}"
end

opts.each { |k,v| puts "#{k}=#{v}" }

