#!/usr/bin/env ruby

# creates symlinks to upstart logs

app_name   = ARGV[0] || 'bugmark'
delay_time = ARGV[1] || 0

abort 'Need App Name!' if app_name.empty?

local_log_dir = File.expand_path('../../../shared/log', __dir__)
umain_log_dir = '/var/log/upstart'

system "rm -f #{local_log_dir}/#{app_name}*.log"
system "sleep #{delay_time}"

Dir.glob("#{umain_log_dir}/#{app_name}*.log").each do |logfile|
  file_name = logfile.split('/').last.gsub('bugmark-','')
  system "ln -s #{logfile} #{local_log_dir}/#{file_name}"
  system "sudo chmod a+rw #{logfile}"
end


