#!/usr/bin/env bash

# download the seed data

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

source script/pair/proxy_ip

echo "=== download ========================================"
echo "downloading seed database from vagrant@$PROXY_IP"
scp  vagrant@$PROXY_IP:seed/data.psql db
echo "downloading seed files from vagrant@$PROXY_IP"
scp vagrant@$PROXY_IP:seed/system.tar.gz public
rm -rf public/system
tar xzf public/system.tar.gz 
echo "Done."
