#!/usr/bin/env bash

# import seed database

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

echo ------- start import -------
date
echo -----------------------------
killall ruby > /dev/null 2>&1
echo ">>>>> Import development database"
bundle exec rake db:drop data:db:import db:migrate 
echo ">>>>> Import test database"
RAILS_ENV=test bundle exec rake db:drop data:db:import db:migrate 
echo ">>>>> Clean test database"
mv public/system public/system.bak
RAILS_ENV=test bundle exec rails runner "TestClean.all"
mv public/system.bak public/system
echo ------- finish import ------
date
echo -----------------------------
