#!/usr/bin/env bash

# run the development server

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

source script/pair/proxy_ip

echo "=== upload ========================================"
ssh vagrant@$PROXY_IP 'mkdir -p seed/system'
echo "Uploading seed database to vagrant@$PROXY_IP"
scp db/data.psql vagrant@$PROXY_IP:seed
echo "Uploading seed files to vagrant@$PROXY_IP"
tar czf /tmp/system.tar.gz public/system
scp /tmp/system.tar.gz vagrant@$PROXY_IP:seed
echo "Done."
