#!/usr/bin/env bash

# call from tmux_console

export APP="DHELLO"

sendkeys() {
  tmux send-keys -t $APP:$1 "$2" C-m
}

splitwin() {
  tmux split-window -v -p $1 -t $APP:$2
}

create_new_session()
{

  tmux new-session -s $APP -n "WEBPACK" -d

  sendkeys 1.1 "clear ; webpack --watch"

  # ----- -----

  tmux new-window -n "TESTRPC"

  sendkeys 2.1 "clear ; testrpc"

  # ----- -----

  tmux new-window -n "TRUFFLE_SERVE"

  sendkeys 3.1 "clear ; truffle serve"

  # ----- -----

  tmux select-window -t $APP:2

}
