#!/usr/bin/env bash

# download_backup

abort() {
  echo "ERROR: ONLY RUNS ON DEVELOPMENT!"
  exit 1
}

echo "||||||||||||||||||||||||||||"
echo ------- start db backup -------
date
echo PWD is `pwd`
echo USER is `whoami`
echo ----------------------------

. ./.env 2> /dev/null
. ~/.bashrc

[[ "$RAILS_ENV" == "development" ]] || abort

# bundle exec rake data:backup:db
# bundle exec cap lch1 data:download:all
rsync -av deploy@lch1:var/backup/lica/lch1 ~/var/backup/lica --delete

echo ------- finish download ------
date
echo ----------------------------

