#!/usr/bin/env bash 

# backup_db

abort() {
  echo "ERROR: ONLY RUNS ON DEVELOPMENT!"
  exit 1
}

echo "||||||||||||||||||||||||||||"
echo ------- start keys backup -------
date
echo PWD is `pwd`
echo USER is `whoami`
echo ----------------------------

. ./.env 2> /dev/null
. ~/.bashrc

[[ "$RAILS_ENV" == "development" ]] || abort

bundle exec rake data:backup:keys

echo ------- finish backup ------
date
echo ----------------------------

