#!/usr/bin/env bash

# call from tmux_console

export APP="BUGMARK-DEV"

sendkeys() {
  tmux send-keys -t $APP:$1 "$2" C-m
}

splitwin() {
  tmux split-window -v -p $1 -t $APP:$2
}

create_new_session()
{

  tmux new-session -s $APP -n "RSPEC" -d

  sendkeys 1.1 'script/dev/specs'

  # ----- -----

  tmux new-window -n "JEST"

  sendkeys 2.1 'jest --watch'

  # ----- -----

  tmux new-window -n "PUMA"

  sendkeys 3.1 'script/dev/puma'

  # ----- -----

  tmux new-window -n "WEBPACK"

  # sendkeys 4.1 'clear ; webpack-dev-server --host 0.0.0.0 --public soak:8080'
  # sendkeys 4.1 'clear ; webpack-dev-server --public'
  sendkeys 4.1 'script/dev/webpack'

  # ----- -----

  # tmux new-window -n "SIDEKIQ"
  #
  # sendkeys 5.1 'script/run/sidekiq'

  # ----- -----

  # tmux new-window -n "TUNNEL"
  #
  # splitwin 70 4
  #
  # sendkeys 6.1 'clear ; rpf deploy@x440h64:3000 3000'

  # ----- -----

  tmux select-window -t $APP:3

}
