#!/usr/bin/env bash

# call from tmux_console

export APP="BUGMARK-DEV"

sendkeys() {
  tmux send-keys -t $APP:$1 "$2" C-m
}

splitwin() {
  tmux split-window -v -p $1 -t $APP:$2
}

create_new_session()
{

  tmux new-session -s $APP -n "RSPEC" -d

  sendkeys 1.1 'script/dev/rspec'

  # ----- -----

  tmux new-window -n "PUMA"

  sendkeys 2.1 'script/dev/puma'

  tmux select-window -t $APP:2

}
