#!/usr/bin/env bash
# should be called from tmux_console

export APP="LOGVIEW"

sendkeys() {
  tmux send-keys -t $APP:$1 "$2" C-m
}

splitwin() {
  tmux split-window -v -p $1 -t $APP:$2
}

create_new_session() {

  tmux new-session -s $APP -n "APPLOG" -d

  splitwin 50 1

  sendkeys 1.1 'sudo journalctl -u bugmark -f'      # system log
  sendkeys 1.2 'cd log; tail -f production.log'  # app log

  # ----- -----

  tmux new-window -n "NGINX"

  splitwin 75 2
  splitwin 50 2

  sendkeys 2.1 'sudo journalctl -u nginx -f'
  sendkeys 2.2 'sudo tail -f /var/log/nginx/access.log'
  sendkeys 2.3 'sudo tail -f /var/log/nginx/error.log'

  # ----- -----

  tmux new-window -n "SIDEKIQ"

  sendkeys 3.1 'sudo journalctl -u sidekiq -f'

  # ----- Open With First Window -----

  tmux select-window -t $APP:1

}
